### ISSUE TITLE
doto focus throws exception for invalid focus

### ISSUE THREAD

**Issue by Dbz** [tksfz/doto2#12]
```
$ doto focus meow
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at com.oracle.svm.reflect.proxies.Proxy_1_Main_main.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:199)
	at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Caused by: java.util.NoSuchElementException: None.get
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.lang.RuntimeException.<init>(RuntimeException.java:62)
	at java.util.NoSuchElementException.<init>(NoSuchElementException.java:57)
	at scala.None$.get(Option.scala:349)
	at scala.None$.get(Option.scala:347)
	at org.tksfz.doto.main.FocusCmdExec$.$anonfun$execute$2(FocusCmdExec.scala:13)
	at org.tksfz.doto.main.FocusCmdExec$$$Lambda$639/1319808567.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:257)
	at org.tksfz.doto.main.FocusCmdExec$.$anonfun$execute$1(FocusCmdExec.scala:12)
	at org.tksfz.doto.main.FocusCmdExec$.$anonfun$execute$1$adapted(FocusCmdExec.scala:7)
	at org.tksfz.doto.main.FocusCmdExec$$$Lambda$545/471612950.apply(Unknown Source)
	at scala.Option.map(Option.scala:146)
	at org.tksfz.doto.main.CmdExec.WithActiveProject(Cmd.scala:38)
	at org.tksfz.doto.main.CmdExec.WithActiveProject$(Cmd.scala:37)
	at org.tksfz.doto.main.FocusCmdExec$.WithActiveProject(FocusCmdExec.scala:5)
	at org.tksfz.doto.main.FocusCmdExec$.execute(FocusCmdExec.scala:7)
	at org.tksfz.doto.main.CmdExec$.execute(Cmd.scala:67)
	at org.tksfz.doto.main.Main$.main(Main.scala:35)
	at org.tksfz.doto.main.Main.main(Main.scala)
	... 4 more
```

**Comment by tksfz** [comment]
Fixed in master
