### ISSUE TITLE
Doto edit exception

### ISSUE THREAD

**Issue by Dbz** [tksfz/doto2#17]
```
$ doto edit fa6904
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at com.oracle.svm.reflect.proxies.Proxy_1_Main_main.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:199)
	at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Caused by: java.nio.file.NoSuchFileException: /var/folders/0x/rms5rjn526x33rm394xwmr8c0000gn/T/doto-5793093427476201999.md
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.io.IOException.<init>(IOException.java:58)
	at java.nio.file.FileSystemException.<init>(FileSystemException.java:73)
	at java.nio.file.NoSuchFileException.<init>(NoSuchFileException.java:61)
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
	at java.nio.file.Files.createTempFile(Files.java:897)
	at better.files.File$.newTemporaryFile(File.scala:1094)
	at org.tksfz.doto.main.EditCmdExec$.editContent(EditCmdExec.scala:51)
	at org.tksfz.doto.main.EditCmdExec$.$anonfun$execute$2(EditCmdExec.scala:21)
	at org.tksfz.doto.main.EditCmdExec$.$anonfun$execute$2$adapted(EditCmdExec.scala:9)
	at org.tksfz.doto.main.EditCmdExec$$$Lambda$664/1380667539.apply(Unknown Source)
	at scala.Option.map(Option.scala:146)
	at org.tksfz.doto.main.EditCmdExec$.$anonfun$execute$1(EditCmdExec.scala:9)
	at org.tksfz.doto.main.EditCmdExec$.$anonfun$execute$1$adapted(EditCmdExec.scala:8)
	at org.tksfz.doto.main.EditCmdExec$$$Lambda$574/297722806.apply(Unknown Source)
	at scala.Option.map(Option.scala:146)
	at org.tksfz.doto.main.CmdExec.WithActiveProject(Cmd.scala:39)
	at org.tksfz.doto.main.CmdExec.WithActiveProject$(Cmd.scala:38)
	at org.tksfz.doto.main.EditCmdExec$.WithActiveProject(EditCmdExec.scala:7)
	at org.tksfz.doto.main.EditCmdExec$.execute(EditCmdExec.scala:8)
	at org.tksfz.doto.main.CmdExec$.execute(Cmd.scala:67)
	at org.tksfz.doto.main.Main$.main(Main.scala:35)
	at org.tksfz.doto.main.Main.main(Main.scala)
	... 4 more
```

**Comment by tksfz** [comment]
fixed and released
