### ISSUE TITLE
Exception when running `doto new`

### ISSUE THREAD

**Issue by Dbz** [tksfz/doto2#7]
```
$ doto new todo
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at com.oracle.svm.reflect.proxies.Proxy_121_Main_main.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:173)
Caused by: java.nio.file.AccessDeniedException: /Users/tk
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.io.IOException.<init>(IOException.java:58)
	at java.nio.file.FileSystemException.<init>(FileSystemException.java:73)
	at java.nio.file.AccessDeniedException.<init>(AccessDeniedException.java:66)
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at better.files.File.createDirectories(File.scala:231)
	at better.files.Dsl$.mkdirs(Dsl.scala:123)
	at org.tksfz.doto.main.InitCmdExec$.init(InitCmdExec.scala:22)
	at org.tksfz.doto.main.NewCmdExec$.execute(NewCmdExec.scala:14)
	at org.tksfz.doto.main.CmdExec$.execute(Cmd.scala:69)
	at org.tksfz.doto.main.Main$.main(Main.scala:35)
	at org.tksfz.doto.main.Main.main(Main.scala)
	... 3 more
```

I think the key line here is: `Caused by: java.nio.file.AccessDeniedException: /Users/tk`. I AM NOT TK- I AM DBZ.

**Comment by tksfz** [comment]
Haha wow did I actually hard-code that into the binary?

**Comment by tksfz** [comment]
This is a funny side-effect of Graal I'm pretty sure. I'll put in a fix right now.

**Comment by tksfz** [comment]
Ok I believe I've fixed it. Can you try re-installing and try again? I'm not sure if brew is smart enough to realize I've published a new release. (I don't change version numbers at this point, although maybe I should.)

**Comment by Dbz** [comment]
Yeah, you should always change the version number. I will brew upgrade and
test again when I get home to my laptop

**Comment by Dbz** [comment]
```
➜ $ brew install doto
==> Installing doto from tksfz/doto
==> Downloading https://github.com/tksfz/doto2/releases/download/v0.1-SNAPSHOT/doto
Already downloaded: /Users/danielburt/Library/Caches/Homebrew/doto-0.1.1-SNAPSHOT
Error: SHA256 mismatch
Expected: 8f871ae2b70e10a77f69488950e7fe083e85782e1e6a34fba534c8e652fb358e
Actual: 4ff27ac931609d39a0651f3995f35805c24b95b5f2c985dba8a90d939ed27851
Archive: /Users/danielburt/Library/Caches/Homebrew/doto-0.1.1-SNAPSHOT
To retry an incomplete download, remove the file above.
```
You need to update the version number each time you make a change. I'll manually fix the issue, but just as an fyi

**Comment by Dbz** [comment]
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at com.oracle.svm.reflect.proxies.Proxy_1_Main_main.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:199)
	at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Caused by: java.nio.file.AccessDeniedException: /Users/thom
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.io.IOException.<init>(IOException.java:58)
	at java.nio.file.FileSystemException.<init>(FileSystemException.java:73)
	at java.nio.file.AccessDeniedException.<init>(AccessDeniedException.java:66)
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at better.files.File.createDirectories(File.scala:231)
	at better.files.Dsl$.mkdirs(Dsl.scala:123)
	at org.tksfz.doto.main.InitCmdExec$.init(InitCmdExec.scala:22)
	at org.tksfz.doto.main.NewCmdExec$.execute(NewCmdExec.scala:14)
	at org.tksfz.doto.main.CmdExec$.execute(Cmd.scala:69)
	at org.tksfz.doto.main.Main$.main(Main.scala:35)
	at org.tksfz.doto.main.Main.main(Main.scala)
	... 4 more
```
Look what I found: `Caused by: java.nio.file.AccessDeniedException: /Users/thom`

**Comment by tksfz** [comment]
OK darn I'll try to fix again and test it.

**Comment by tksfz** [comment]
OK it's fixed for real now. Let me know how it goes. Thanks for bearing with me!

**Comment by Dbz** [comment]
`Error: tksfz/doto/doto 0.1 already installed`

I'll try removing it and reinstalling.

**Comment by Dbz** [comment]
Command worked!
